### ISSUE TITLE
got rejected on ask

### ISSUE THREAD

**Issue by Sunda001** [EvanZhouDev/palm-api#7]
```
Error: Request rejected. Got [object Object] instead of response.
    at Chat.ask (file:///root/hisoka-baileys/node_modules/palm-api/out/index.js:269:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Module.Message (file:///root/hisoka-baileys/event/message.js?v=1697783348701:798:35)
    at async EventEmitter.<anonymous> (file:///root/hisoka-baileys/hisoka.js:250:7)

**Comment by freitassdev** [comment]
Did you find any solution for this?
